chore(github): added docker build&push for k8s mcp
Signed-off-by: Mohamed Tahar KEDJOUR <mkedjour@cisco.com>

diff --git a/.github/workflows/push-k8s-demo.yml b/.github/workflows/push-k8s-demo.yml
--- a/.github/workflows/push-k8s-demo.yml
+++ b/.github/workflows/push-k8s-demo.yml
@@ -83,3 +83,45 @@ jobs:
       ecr-enabled: true
       artifactory-devhub-enabled: true
       ghcr-enabled: false
+
+  docker-build-push-k8s-mcp:
+    name: Build & Push k8s demo mcp
+    needs: [prepare-release]
+    uses: cisco-eti/gh-reusable-workflows/.github/workflows/build-push-docker.yaml@production
+    secrets:
+      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
+      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
+      ghcr-username: ${{ secrets.GHCR_USERNAME }}
+      ghcr-token: ${{ secrets.GHCR_TOKEN }}
+      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
+    with:
+      runner-group: arc-runner-set
+      image-name: "outshift-zta/k8s-demo-mcp"
+      image-custom-tag: ${{ needs.prepare-release.outputs.version }}
+      context: demo/k8s/mcp
+      dockerfile: demo/k8s/mcp/Dockerfile
+      ecr-enabled: true
+      artifactory-devhub-enabled: true
+      ghcr-enabled: false
+
+  reusable-workflow-ci-status:
+    name: Reusable Workflow CI Status
+    # This should be an array of ALL active jobs that are used/run
+    needs: [
+      checkout,
+      docker-build-push-k8s-agent,
+      docker-build-push-k8s-mcp
+    ]
+    if: always()
+    runs-on:
+      group: arc-runner-set
+    steps:
+      - name: report failure
+        if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+        run: |
+          echo -e "\033[31m*** WORKFLOW FAILED ***\033[0m"
+          exit 1
+      - name: report success
+        run: |
+          echo -e "\033[1;36m*** WORKFLOW SUCCEEDED ***\033[0m"
+          exit 0
